In [1]:
import gzip
import json
import dateutil.parser
import random

In [20]:
import homework1

In [21]:
root = "../DSC_258/data"

In [22]:
f = gzip.open(root + "/fantasy_10000.json.gz")
dataset = []
for l in f:
    dataset.append(json.loads(l))

In [23]:
dataset[0]

{'user_id': '8842281e1d1347389f2ab93d60773d4d',
 'book_id': '18245960',
 'review_id': 'dfdbb7b0eb5a7e4c26d59a937e2e5feb',
 'rating': 5,
 'review_text': 'This is a special book. It started slow for about the first third, then in the middle third it started to get interesting, then the last third blew my mind. This is what I love about good science fiction - it pushes your thinking about where things can go. \n It is a 2015 Hugo winner, and translated from its original Chinese, which made it interesting in just a different way from most things I\'ve read. For instance the intermixing of Chinese revolutionary history - how they kept accusing people of being "reactionaries", etc. \n It is a book about science, and aliens. The science described in the book is impressive - its a book grounded in physics and pretty accurate as far as I could tell. Though when it got to folding protons into 8 dimensions I think he was just making stuff up - interesting to think about though. \n But what would 

In [24]:
for d in dataset:
    t = dateutil.parser.parse(d['date_added'])
    d['parsed_date'] = t

In [25]:
dataset[0]

{'user_id': '8842281e1d1347389f2ab93d60773d4d',
 'book_id': '18245960',
 'review_id': 'dfdbb7b0eb5a7e4c26d59a937e2e5feb',
 'rating': 5,
 'review_text': 'This is a special book. It started slow for about the first third, then in the middle third it started to get interesting, then the last third blew my mind. This is what I love about good science fiction - it pushes your thinking about where things can go. \n It is a 2015 Hugo winner, and translated from its original Chinese, which made it interesting in just a different way from most things I\'ve read. For instance the intermixing of Chinese revolutionary history - how they kept accusing people of being "reactionaries", etc. \n It is a book about science, and aliens. The science described in the book is impressive - its a book grounded in physics and pretty accurate as far as I could tell. Though when it got to folding protons into 8 dimensions I think he was just making stuff up - interesting to think about though. \n But what would 

In [26]:
dataset4 = dataset[:]
random.seed(0)
random.shuffle(dataset4)

In [27]:
f = open("../DSC_258/data/beer_50000.json")
datasetB = []
for l in f:
    datasetB.append(eval(l))

In [28]:
datasetB[0]

{'review/appearance': 2.5,
 'beer/style': 'Hefeweizen',
 'review/palate': 1.5,
 'review/taste': 1.5,
 'beer/name': 'Sausa Weizen',
 'review/timeUnix': 1234817823,
 'beer/ABV': 5.0,
 'beer/beerId': '47986',
 'beer/brewerId': '10325',
 'review/timeStruct': {'isdst': 0,
  'mday': 16,
  'hour': 20,
  'min': 57,
  'sec': 3,
  'mon': 2,
  'year': 2009,
  'yday': 47,
  'wday': 0},
 'review/overall': 1.5,
 'review/text': 'A lot of foam. But a lot.\tIn the smell some banana, and then lactic and tart. Not a good start.\tQuite dark orange in color, with a lively carbonation (now visible, under the foam).\tAgain tending to lactic sourness.\tSame for the taste. With some yeast and banana.',
 'user/profileName': 'stcules',
 'review/aroma': 2.0}

In [29]:
def testQ1():
    theta1, MSE1 = homework1.Q1(dataset)
    # The autograder will compare these answers to a reference solution
    print(theta1)
    print(MSE1)

In [30]:
def testQ2():
    X, Y, MSE = homework1.Q2(dataset)
    print((X[0],Y[0],MSE))

In [31]:
def testQ3():
    X, Y, MSE = homework1.Q3(dataset)
    print((X[0],Y[0],MSE))

In [15]:
def testQ4():
    test_mse2, test_mse3 = homework1.Q4(dataset4)
    print((test_mse2, test_mse3))

In [16]:
def testQ5():
    TP, TN, FP, FN, BER = homework1.Q5(datasetB, homework1.featureQ5)
    print((TP, TN, FP, FN, BER))

In [17]:
def testQ6():
    precs = homework1.Q6(datasetB)
    print(precs)

In [18]:
def testQ7():
    _, _, _, _, BER5 = homework1.Q5(datasetB, homework1.featureQ5)
    _, _, _, _, BER7 = homework1.Q5(datasetB, homework1.featureQ7)
    print((BER5,BER7))

In [32]:
testQ1()

first record of lengths: 2086
longest length review: 14306
[3.68568136 0.98335392]
1.5522086622355356


/Users/mattzidell/Documents/GitHub/DSC_258/.venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: divide by zero encountered in matmul
  return X @ coef_ + self.intercept_
/Users/mattzidell/Documents/GitHub/DSC_258/.venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: overflow encountered in matmul
  return X @ coef_ + self.intercept_
/Users/mattzidell/Documents/GitHub/DSC_258/.venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: invalid value encountered in matmul
  return X @ coef_ + self.intercept_


In [33]:
testQ2()

first record of lengths: 2086
longest length review: 14306
Fri
['Mon' 'Sat' 'Sun' 'Thu' 'Tue' 'Wed']
Number of Unique Days: 7
Dimensions of Hot Encoded DOW feature: 6
(10000, 1)
1
[ 2  3  4  5  6  7  8  9 10 11 12]
Number of Unique Months: 12
Dimensions of Hot Encoded DOW feature: 11
(10000, 1)
(array([1.        , 0.14581295, 0.        , 0.        , 1.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 1.        , 0.        ,
       0.        , 0.        , 0.        , 0.        ]), np.int64(5), np.float64(1.546631549848753))


/Users/mattzidell/Documents/GitHub/DSC_258/.venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: divide by zero encountered in matmul
  return X @ coef_ + self.intercept_
/Users/mattzidell/Documents/GitHub/DSC_258/.venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: overflow encountered in matmul
  return X @ coef_ + self.intercept_
/Users/mattzidell/Documents/GitHub/DSC_258/.venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: invalid value encountered in matmul
  return X @ coef_ + self.intercept_


In [34]:
testQ3()

first record of lengths: 2086
longest length review: 14306
(array([   1, 2086,    6,    7]), np.int64(5), np.float64(1.5516353711453312))


/Users/mattzidell/Documents/GitHub/DSC_258/.venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: divide by zero encountered in matmul
  return X @ coef_ + self.intercept_
/Users/mattzidell/Documents/GitHub/DSC_258/.venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: overflow encountered in matmul
  return X @ coef_ + self.intercept_
/Users/mattzidell/Documents/GitHub/DSC_258/.venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: invalid value encountered in matmul
  return X @ coef_ + self.intercept_


In [ ]:
testQ4()

In [ ]:
testQ5()

In [ ]:
testQ6()

In [ ]:
testQ7()